@endpoint = https://w80d2j0819.execute-api.ap-northeast-1.amazonaws.com/prod/

GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces?spaceId=19f4bfe8-b2f7-4be2-b2c3-7f0f0e5355da
###

GET {{endpoint}}/spaces?location=London
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
  "location": "London",
  "name": "Best Location"
}
###